version: '3.9'
services:
  checker:
    build: .
    ports:
      - "8080:3000"
    volumes:
      - type: bind
        source: ./sqlite.db
        target: /app/sqlite.db
      - type: bind
        source: ./config.json
        target: /app/config.json
