version: '3.9'
services:
  checker:
    build: .
    volumes:
      - type: bind
        source: ./records.json
        target: /app/records.json
      - type: bind
        source: ./config.json
        target: /app/config.json
