version: '3.9'
services:
  checker:
    build: .
    ports:
      - '3020:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - type: bind
        source: ./sqlite.db
        target: /app/sqlite.db
      - type: bind
        source: ./config.json
        target: /app/config.json
